"""add location

Revision ID: 3c5604374ec6
Revises: ce30373ff1fc
Create Date: 2018-08-16 12:41:13.150587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5604374ec6'
down_revision = 'ce30373ff1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'location')
    # ### end Alembic commands ###
