"""empty message

Revision ID: b6d4bfa3b6ec
Revises: 3c5604374ec6
Create Date: 2018-09-24 08:43:43.991565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d4bfa3b6ec'
down_revision = '3c5604374ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lattitude', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('longitude', sa.String(length=100), nullable=True))
    op.drop_column('user', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('user', 'longitude')
    op.drop_column('user', 'lattitude')
    # ### end Alembic commands ###
